# Generated by Django 3.0.1 on 2019-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CICD',
            fields=[
                ('tech', models.CharField(max_length=20)),
                ('deploy_date', models.DateField()),
                ('environment', models.CharField(max_length=30)),
                ('machine_name', models.CharField(max_length=30)),
                ('classifier', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
