# Generated by Django 3.0.1 on 2019-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicd',
            name='smoke_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cicd',
            name='smoke_test_status',
            field=models.BooleanField(default=False),
        ),
    ]
